# Generated by Django 3.1.7 on 2021-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.AddField(
            model_name='genre',
            name='film',
            field=models.ManyToManyField(to='films.Film'),
        ),
    ]
