# Generated by Django 3.1.7 on 2021-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20210408_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='film',
            field=models.ManyToManyField(null=True, to='films.Film'),
        ),
    ]
