# Generated by Django 3.1.7 on 2021-04-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20210408_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
