# Generated by Django 3.1.7 on 2021-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_auto_20210408_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='kp_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
