# Generated by Django 4.0.5 on 2022-06-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_film_kp_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='КиноПоиск id'),
        ),
        migrations.AlterField(
            model_name='film',
            name='numMarks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='raiting',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
