# Generated by Django 3.1.7 on 2021-04-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_validation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='validation_code',
            new_name='key',
        ),
    ]
