# Generated by Django 4.0.5 on 2022-06-10 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_profile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberOfMarks',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberOfRecensions',
            field=models.IntegerField(default=0, verbose_name='Количество рецензий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Репутация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
