# Generated by Django 3.1.7 on 2021-05-02 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20210501_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmrecension',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serialrecension',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
