# Generated by Django 3.1.4 on 2021-02-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210219_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialvoter',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='serialvoter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seriya',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='film',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='Serial',
        ),
        migrations.DeleteModel(
            name='SerialVoter',
        ),
        migrations.DeleteModel(
            name='Seriya',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
