# Generated by Django 3.1.7 on 2021-04-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20210408_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.AddField(
            model_name='genre',
            name='film',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
