# Generated by Django 3.1.7 on 2021-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20210312_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='kp_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
