# Generated by Django 4.0.5 on 2022-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_serial_kp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='kp_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
