# Generated by Django 4.0.5 on 2022-06-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_alter_serial_kp_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.AlterModelOptions(
            name='seriya',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterField(
            model_name='serial',
            name='count_sesonov',
            field=models.IntegerField(default=1, verbose_name='Количество сезонов'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='kp_id',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='КиноПоиск id'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='numMarks',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='raiting',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seriya',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='seriya',
            name='season',
            field=models.IntegerField(verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='seriya',
            name='serial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='serials.serial', verbose_name='Сериал'),
        ),
        migrations.AlterField(
            model_name='seriya',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seriya',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
