# Generated by Django 3.1.7 on 2021-05-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_filmrecension_serialrecension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmrecension',
            name='text',
        ),
        migrations.RemoveField(
            model_name='serialrecension',
            name='text',
        ),
    ]
